"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - LF_hip_joint
          - LF_upper_leg_joint
          - LF_lower_leg_joint
          - RF_hip_joint
          - RF_upper_leg_joint
          - RF_lower_leg_joint
          - LH_hip_joint
          - LH_upper_leg_joint
          - LH_lower_leg_joint
          - RH_hip_joint
          - RH_upper_leg_joint
          - RH_lower_leg_joint

      gains:
        LF_hip_joint : {p: 800, d: 90.0, i: 300}
        LF_upper_leg_joint : {p: 800, d: 90.0, i: 300}
        LF_lower_leg_joint : {p: 800, d: 90.0, i: 300}
        RF_hip_joint : {p: 800, d: 90.0, i: 300}
        RF_upper_leg_joint : {p: 800, d: 90.0, i: 300}
        RF_lower_leg_joint : {p: 800, d: 90.0, i: 300}
        LH_hip_joint : {p: 800, d: 90.0, i: 300}
        LH_upper_leg_joint : {p: 800, d: 90.0, i: 300}
        LH_lower_leg_joint : {p: 800, d: 90.0, i: 300}
        RH_hip_joint : {p: 800, d: 90.0, i: 300}
        RH_upper_leg_joint : {p: 800, d: 90.0, i: 300}
        RH_lower_leg_joint : {p: 800, d: 90.0, i: 300}
