rectified: true

numOfFrames: 657

multi: false

gtPose : true

leftPathCam : "/front/zed_node/left/image_rect_color"
rightPathCam : "/front/zed_node/right/image_rect_color"

leftPathCamB : "/camera_4/left/image_rect"
rightPathCamB : "/camera_4/right/image_rect"

aprilTagPath : "tag_detections_2"

gtPath : "front/zed_node/odom"

imagesPath: "/home/christos/catkin_ws/src/mini_project_kokas/src/vio_slam/images/"

fileExtension: ".jpg"



Camera_l:
  fx: 528.4699096679688
  fy: 528.4699096679688
  cx: 485.1518249511719
  cy: 282.48875244140625
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

Camera_l_path: /zed2i/zed_node/left_raw/image_raw_color
# /zed2i/zed_node/left_raw/image_raw_color
# /camera_1/left/image_raw

Camera_r:
  fx: 528.4699096679688
  fy: 528.4699096679688
  cx: 485.1518249511719
  cy: 282.48875244140625
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  
Camera_r_path: /zed2i/zed_node/right_raw/image_raw_color
# /zed2i/zed_node/right_raw/image_raw_color
# /camera_1/right/image_raw

Camera:
  width: 960
  height: 540
  fps: 15.0
  bl: 0.119783

CameraB_l:
  fx: 130.55877685546875
  fy: 130.55877685546875
  cx: 172.13943481445312
  cy: 94.27045440673828
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

CameraB_l_path: /zed2i/zed_node/left_raw/image_raw_color
# /zed2i/zed_node/left_raw/image_raw_color
# /camera_1/left/image_raw

CameraB_r:
  fx: 130.55877685546875
  fy: 130.55877685546875
  cx: 172.13943481445312
  cy: 94.27045440673828
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  
CameraB_r_path: /zed2i/zed_node/right_raw/image_raw_color
# /zed2i/zed_node/right_raw/image_raw_color
# /camera_1/right/image_raw

CameraB:
  width: 960
  height: 540
  fps: 15.0
  bl: 0.119783

Camera_path: /zed2i/zed_node/left_raw/image_raw_color
ground_truth_path: /odom/ground_truth/2
pointcloud_path: /camera_1/points2

IMU:
  T_b_c1: 
    rows: 4
    cols: 4
    dt: f
    data: [  0.0040000, -0.0000080,  0.9999920, -0.008,
            -0.9999840,  0.0040000,  0.0040000, 0.023,
            -0.0040000, -0.9999920,  0.0000080, -0.000,
            0.0, 0.0, 0.0, 1.0]
  path: /imu/data

Stereo:
  T_c1_c2:
    rows: 4
    cols: 4
    dt: f
    data: [1.0, 0.0, 0.0, -0.119947,
         0.0, 1.0, 0.0, 0.00037599,
         0.0, 0.0, 1.0, -0.000147674,
         0.0, 0.0, 0.0, 1.0]

T_w_c1:
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.150,
        -1.0, 0.0, 0.0, -0.06,
        0.0, -1.0, 0.0, -0.20,
        0.0, 0.0, 0.0, 1.0]

Multi:
  T_c1_c2:
    rows: 4
    cols: 4
    dt: d
    data: [-1.0, 0.0, 0.0, 0.12,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, -1.0, -0.3,
         0.0, 0.0, 0.0, 1.0]

T_bf_c1:
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.150,
        -1.0, 0.0, 0.0, 0.06,
        0.0, -1.0, 0.0, 0.25,
        0.0, 0.0, 0.0, 1.0]

# T_c1_bf:
#   rows: 4
#   cols: 4
#   dt: d
#   data: [0.0, -1.0, 0.0, 0.06,
#         0.0, 0.0, -1.0, 0.25,
#         1.0, .0, 0.0, -0.15,
#         0.0, 0.0, 0.0, 1.0]

LCSameCam : false

T_c1_AT:
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.246,
        0.0, 1.0, 0.0, 0.0,
        -1.0, 0.0, 0.0, -0.24,
        0.0, 0.0, 0.0, 1.0]


tagPose : false

T_w_tag:
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.210,
        0.0, 1.0, 0.0, 0.0,
        -1.0, 0.0, 0.0, -0.09,
        0.0, 0.0, 0.0, 1.0]

T_tag_b:
  rows: 4
  cols: 4
  dt: d
  data: [-1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 1.0, 0.0, 0.3,
        0.0, 0.0, 0.0, 1.0]
