rectified: true

numOfFrames: 657

multi: false

gtPose : false

leftPathCam : "/zed2i/zed_node/left/image_rect_color"
rightPathCam : "/zed2i/zed_node/right/image_rect_color"

leftPathCamB : "/camera_4/left/image_rect"
rightPathCamB : "/camera_4/right/image_rect"

aprilTagPath : "tag_detections"

imagesPath: "/home/christos/catkin_ws/src/mini_project_kokas/src/vio_slam/images/"

fileExtension: ".jpg"



Camera_l:
  fx: 261.403
  fy: 261.403
  cx: 325.983
  cy: 180.828
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

Camera_l_path: /zed2i/zed_node/left_raw/image_raw_color
# /zed2i/zed_node/left_raw/image_raw_color
# /camera_1/left/image_raw

Camera_r:
  fx: 261.403
  fy: 261.403
  cx: 325.983
  cy: 180.828
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  
Camera_r_path: /zed2i/zed_node/right_raw/image_raw_color
# /zed2i/zed_node/right_raw/image_raw_color
# /camera_1/right/image_raw

Camera:
  width: 640
  height: 360
  fps: 15.0
  bl: 0.119947

CameraB_l:
  fx: 265.795
  fy: 265.6975
  cx: 338.7225
  cy: 186.95575
  k1: -0.0420501
  k2: 0.0107849
  p1: 0.000333607
  p2: 0.000225869
  k3: -0.0052130

CameraB_l_path: /zed2i/zed_node/left_raw/image_raw_color
# /zed2i/zed_node/left_raw/image_raw_color
# /camera_1/left/image_raw

CameraB_r:
  fx: 264.59
  fy: 264.325
  cx: 337.56
  cy: 188.85625
  k1: -0.0416772
  k2: 0.0101824
  p1: -1.93738e-05
  p2: -0.000249686
  k3: -0.00489882
  
CameraB_r_path: /zed2i/zed_node/right_raw/image_raw_color
# /zed2i/zed_node/right_raw/image_raw_color
# /camera_1/right/image_raw

CameraB:
  width: 640
  height: 360
  fps: 15.0
  bl: 0.119947

Camera_path: /zed2i/zed_node/left_raw/image_raw_color
ground_truth_path: /odom/ground_truth/2
pointcloud_path: /camera_1/points2

IMU:
  T_b_c1: 
    rows: 4
    cols: 4
    dt: f
    data: [  0.0040000, -0.0000080,  0.9999920, -0.008,
            -0.9999840,  0.0040000,  0.0040000, 0.023,
            -0.0040000, -0.9999920,  0.0000080, -0.000,
            0.0, 0.0, 0.0, 1.0]
  path: /imu/data

Stereo:
  T_c1_c2:
    rows: 4
    cols: 4
    dt: f
    data: [1.0, 0.0, 0.0, -0.119947,
         0.0, 1.0, 0.0, 0.00037599,
         0.0, 0.0, 1.0, -0.000147674,
         0.0, 0.0, 0.0, 1.0]

T_w_c1:
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.150,
        -1.0, 0.0, 0.0, -0.06,
        0.0, -1.0, 0.0, -0.20,
        0.0, 0.0, 0.0, 1.0]

Multi:
  T_c1_c2:
    rows: 4
    cols: 4
    dt: d
    data: [-1.0, 0.0, 0.0, 0.12,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, -1.0, -0.3,
         0.0, 0.0, 0.0, 1.0]
