rectified: true

Camera_l:
  fx: 529.14
  fy: 529.085
  cx: 628.47
  cy: 352.763
  k1: -0.0398087
  k2: 0.00800801
  p1: 7.87786e-05
  p2: -0.000224249
  k3: -0.00421763

Camera_l_path: /zed2i/zed_node/left_raw/image_raw_color
# /zed2i/zed_node/left_raw/image_raw_color
# /camera_1/left/image_raw

Camera_r:
  fx: 529.71
  fy: 529.415
  cx: 629.01
  cy: 350.612
  k1: -0.0437957
  k2: 0.0130789
  p1: -4.03403e-05
  p2: -0.00021063
  k3: -0.00607482
  
Camera_r_path: /zed2i/zed_node/right_raw/image_raw_color
# /zed2i/zed_node/right_raw/image_raw_color
# /camera_1/right/image_raw

Camera:
  width: 1280
  height: 720
  fps: 15.0
  bl: 0.119848

Camera_path: /zed2i/zed_node/left_raw/image_raw_color
ground_truth_path: /odom/ground_truth/2
pointcloud_path: /camera_1/points2

IMU:
  T_b_c1: 
    rows: 4
    cols: 4
    dt: f
    data: [  0.0040000, -0.0000080,  0.9999920, -0.008,
            -0.9999840,  0.0040000,  0.0040000, 0.023,
            -0.0040000, -0.9999920,  0.0000080, -0.000,
            0.0, 0.0, 0.0, 1.0]
  path: /imu/data

Stereo:
  T_c1_c2:
    rows: 4
    cols: 4
    dt: f
    data: [1.0, 0.0, 0.0, -0.119848,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]